@isTest
public class TestClass {
    public static testmethod void testMyClass()
    {
        Account act = new Account(Name= 'akhil');
        Insert act;
        Contact conObj = new Contact(lastname='santimoy', accountId = act.Id);
        insert conObj;
        Contact conObj1 = new Contact(lastname ='santio');
        INSERT conObj1;
        conObj1.FirstName = 'gsadsfcsdffgd';
        update conObj1;
        DELETE conObj1;
    }
    
}